### ISSUE TITLE
how to start game

### ISSUE THREAD

**Issue by soans1994** [adajani/dave-trainer#1]
hello,

how can i start the game. trainer.exe doesnt open in windoes 10. should i use script?

**Comment by soans1994** [comment]
i tried tildt ~ key in game nothing happens

**Comment by adajani** [comment]
Hi
Download the DosBox, and Copy the dave.exe from the internet and put the trainer in same folder and have fun!

**Comment by adajani** [comment]
Hi
Download the DosBox, and Copy the dave.exe from the internet and put the trainer in same folder and have fun!
